import { FC, PropsWithChildren } from "react";
import type { Metadata } from "next";
import './globals.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return <html lang="en">{children}</html>;
};

export default RootLayout;
